features:
  oidcAuth: true
  defaultBucket: true
  
image:
  tag: latest
  repository: image-registry.openshift-image-registry.svc:5000/df9936-tools
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

config:
  enabled: true
  releaseScoped: true
  configMap:
    BASICAUTH_ENABLED: "true"
    DB_PORT: "5432"
    KC_ENABLED: "true"
    KC_IDENTITYKEY: idir_user_guid,bceid_user_guid,github_id
    KC_PUBLICKEY: >-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFdv9GA83uHuy8Eu9yiZHGGF9j6J8t7FkbcpaN81GDjwbjsIJ0OJO9dKRAx6BAtTC4ubJTBJMPvQER5ikOhIeBi4o25fg61jpgsU6oRZHkCXc9gX6mrjMjbsPaf3/bjjYxP5jicBDJQeD1oRa24+tiGggoQ7k6gDEN+cRYqqNpzC/GQbkUPk8YsgroncEgu8ChMh/3ERsLV2zorchMANUq76max16mHrhtWIQxrb/STpSt4JuSlUzzBV/dcXjJe5gywZHe0jAutFhNqjHzHdgyaC4RAd3eYQo+Kl/JOgy2AZrnx+CiPmvOJKe9tAW4k4H087ng8aVE40v4HW/FEbnwIDAQAB
    KC_REALM: standard
    KC_SERVERURL: "https://test.loginproxy.gov.bc.ca/auth"
    OBJECTSTORAGE_BUCKET: data-bcstats-lockbox-test-bkt
    OBJECTSTORAGE_ENDPOINT: "https://bc-stats-obj.objectstore.gov.bc.ca"
    OBJECTSTORAGE_KEY: X
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"
    SERVER_PRIVACY_MASK: "true"
    SERVER_TEMP_EXPIRESIN: "300"

patroni:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 250m
      memory: 384Mi
    requests:
      cpu: 20m
      memory: 192Mi
  persistentVolume:
    enabled: true
    size: 128Mi
