---
features:
  basicAuth: true
  oidcAuth: true

image:
  tag: latest
  repository: image-registry.openshift-image-registry.svc:5000/df9936-tools
  pullPolicy: Always

config:
  enabled: true
  configMap:
    BASICAUTH_ENABLED: "true"
    DB_PORT: "5432"
    KC_ENABLED: "true"
    KC_IDENTITYKEY: idir_user_guid,bceid_user_guid,github_id
    KC_PUBLICKEY: >-
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuy7zfh2ZgpDV5mH/aXyLDTddZK81rGakJcTy4KvCNOkDDxt1KAhW02lmbCo8YhHCOzjNZBp1+Vi6QiMRgBqAe2GTPZYEiV70aXfROGZe3Nvwcjbtki6HoyRte3SpqLJEIPL2F+hjJkw1UPGnjPTWZkEx9p74b9i3BjuE8RnjJ0Sza2MWw83zoQUZEJRGiopSL0yuVej6t2LO2btVdVf7QuZfPt9ehkcQYlPKpVvJA+pfeqPAdnNt7OjEIeYxinjurZr8Z04hz8UhkRefcWlSbFzFQYmL7O7iArjW0bsSvq8yNUd5r0KCOQkFduwZy26yTzTxj8OLFT91fEmbBBl4rQIDAQAB
    KC_REALM: standard
    KC_SERVERURL: "https://dev.loginproxy.gov.bc.ca/auth"
    OBJECTSTORAGE_BUCKET: data-bcstats-lockbox-dev-bkt
    OBJECTSTORAGE_TEMP_EXPIRESIN: "300"
    OBJECTSTORAGE_ENDPOINT: "https://bc-stats-obj.objectstore.gov.bc.ca"
    #OBJECTSTORAGE_KEY: ~
    SERVER_BODYLIMIT: 30mb
    SERVER_LOGLEVEL: http
    SERVER_PORT: "3000"
    SERVER_PRIVACY_MASK: "true"

patroni:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 250m
      memory: 384Mi
    requests:
      cpu: 20m
      memory: 192Mi
  persistentVolume:
    enabled: false
    size: 128Mi
