{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aps-gateway-allow-traffic-{{ include "coms.fullname" . }}-app
  labels:
    {{- include "coms.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: 264e6f
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: 264e6f
        - namespaceSelector:
            matchLabels:
              environment: test
              name: b8840c
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: b8840c
        - podSelector:
            matchLabels: {{ include "coms.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "8080" .Values.config.configMap.SERVER_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{- include "coms.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- if .Values.patroni.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "coms.fullname" . }}-app-to-{{ include "patroni.fullname" .Subcharts.patroni }}-cluster
  labels: {{ include "patroni.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels: {{ include "coms.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "5432" .Values.config.configMap.DB_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{ include "patroni.selectorLabels" .Subcharts.patroni | nindent 6 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pre-hook-to-{{ include "patroni.fullname" .Subcharts.patroni }}-cluster
  labels: {{ include "patroni.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              openshift.io/deployer-pod.type: hook-pre
      ports:
        - port: {{ default "5432" .Values.config.configMap.DB_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{ include "patroni.selectorLabels" .Subcharts.patroni | nindent 6 }}
{{- end }}
{{- end }}
